# Generated by Django 5.0.6 on 2024-05-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationApp', '0002_userinterests'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='comment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='love',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='share',
            field=models.IntegerField(default=0),
        ),
    ]
