# Generated by Django 5.0.6 on 2024-05-10 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationApp', '0003_video_comment_video_love_video_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recommendationApp.account'),
            preserve_default=False,
        ),
    ]
