# Generated by Django 5.0.6 on 2024-05-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationApp', '0006_alter_userinterests_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterests',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
