# Generated by Django 5.0.6 on 2024-05-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationApp', '0008_alter_userinfo_user_alter_video_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='comment',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='love',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='share',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
